Repository bigcommerce/dev-docs, pull requests merged in 2022-06, with the labels that each got.

#1489 DEVDOCS-3979 / DEVDOCS-3779: Update Dev Docs to replace `config_meta` w /channel-menus
  docs/api-docs/channels/channels-quick-start.md
  docs/api-docs/channels/channels-storefront-tutorial.md
Labels: from-engineering

#1457 DEVDOCS-3807: Update checkout-sdk
  docs/api-docs/cart-and-checkout/checkout-sdk.md
Labels: ready-to-merge

#1471 DEVDOCS-3803: Update payments-api-overview
  docs/api-docs/payments/payments-api-overview.md
Labels: ready-to-merge

#1405 DEVDOCS-3406: Revise OAuth and API account articles
  docs/api-docs/getting-started/authentication.md
  docs/api-docs/getting-started/rest-api-authentication.md
  toc.json
Labels: awaiting-final-review, extensive-revisions

#1544 Added .po files to localizing-stores.md
  docs/stencil-docs/localization/localizing-stores.md
Labels: awaiting-final-review, awaiting-peer-review

#1549 DEVDOCS-3876 Update app guide with MSF app profile options
  docs/api-docs/apps/guide/apps-04-devloper-portal.md
  docs/api-docs/apps/guide/apps-13-publishing.md
  docs/api-docs/getting-started/authentication.md
  docs/api-docs/getting-started/rest-api-authentication.md
  docs/msf/msf-app-compatibility.md
Labels: awaiting-final-review

#1548 DEVDOCS-4026 add commonwealth bank to payments-api-overview
  docs/api-docs/payments/payments-api-overview.md
Labels: do-not-merge, awaiting-css-cue

#1550 DEVDOCS-4132: Update payments-api-overview
  docs/api-docs/payments/payments-api-overview.md
Labels: do-not-merge, awaiting-css-cue
