Repository bigcommerce/dev-docs, pull requests merged in 2022-04, with the labels that each got.

#1426 DEVDOCS-3021: Update Channel-webhooks
  docs/api-docs/channels/channel-webhooks.md
Labels: awaiting-creator-rereview, awaiting-css-cue

#1437 DEVDOCS-3664: broken links
  docs/api-docs/catalog/v2-vs-v3.md
Labels: ready-to-merge

#1441 DEVDOCS-3702: Update payments-api-overview
  docs/api-docs/payments/payments-api-overview.md
Labels: awaiting-final-review, awaiting-creator-rereview

#1448 style guide, cleaner form, link channels section to MSF-aware channels webhooksarticle
  docs/api-docs/getting-started/webhooks/webhook-events.md
Labels: awaiting-final-review

#1452 DEVDOCS-3764-update-cart-and-checkout-tutorial
  docs/api-docs/cart-and-checkout/working-sf-apis.md
Labels: awaiting-final-review, awaiting-peer-review

#1456 DEVDOCS-3780-update-link
  docs/api-docs/headless/pci-compliance.md
Labels: Maintenance, awaiting-final-review, awaiting-peer-review

#1453 DEVDOCS-3719 Add channel_id to the payload fields reference
  docs/api-docs/cart-and-checkout/embedded-checkout-tutorial.md
  docs/api-docs/customers/customer-login-api.md
Labels: awaiting-final-review

#1455 DEVDOCS-3787-add-API-option
  docs/api-docs/cart-and-checkout/custom-order-confirmation.md
  docs/api-docs/cart-and-checkout/open-source-checkout.md
Labels: awaiting-final-review, ready-to-merge

#1460 DEVDOCS-3702: Update payments-api-overview
  docs/api-docs/payments/payments-api-overview.md
Labels: awaiting-final-review

#1425 DEVDOCS-3496: html to md
  docs/legacy/blueprint-themes/blueprint-and-developer-mode.md
  docs/legacy/blueprint-themes/blueprint-email-templates.md
  docs/legacy/blueprint-themes/lng-variables.md
  docs/stencil-docs/deploying-a-theme/troubleshooting-theme-uploads.md
Labels: awaiting-final-review

#1461 3021B: about webhooks scope creep
  docs/api-docs/channels/channel-webhooks.md
  docs/api-docs/getting-started/webhooks/about-webhooks.md
Labels: awaiting-final-review

#1466 Update webhook-events.md
  docs/api-docs/getting-started/webhooks/webhook-events.md
Labels: awaiting-final-review, awaiting-peer-review, ready-to-merge

#1462 DEVDOCS-3715: Node 12 EOL
  docs/api-docs/apps/apps-quick-start.md
  docs/partner-apps/bundleb2b/b2b-edition.md
  docs/stencil-docs/installing-stencil-cli/installing-stencil.md
Labels: awaiting-final-review, ready-to-merge

#1478 DEVDOCS-3759: date payment gateways link
  docs/api-docs/headless/checkout.md
Labels: awaiting-final-review, awaiting-pe-sme-review, awaiting-peer-review

#1376 DEVDOCS-3398: Create BODL.md
  docs/api-docs/analytics/bodl-overview.md
Labels: awaiting-final-review
