Repository bigcommerce/dev-docs, pull requests merged in 2022-07, with the labels that each got.

#1555 DEVDOCS-4238: Update theme-best-practices.md
  docs/stencil-docs/deploying-a-theme/theme-best-practices.md
Labels: broken-links, awaiting-final-review, ready-to-merge

#1475 DEVDOCS-2898: Document JWTs
  docs/api-docs/apps/guide/apps-01-introduction.md
  docs/api-docs/apps/guide/apps-02-types.md
  docs/api-docs/apps/guide/apps-03-developing.md
  docs/api-docs/apps/guide/apps-05-oauth.md
  docs/api-docs/apps/guide/apps-06-callbacks.md
  docs/api-docs/apps/guide/apps-07-users.md
  docs/api-docs/apps/guide/apps-08-events.md
  docs/api-docs/apps/guide/apps-09-ui.md
  docs/api-docs/apps/guide/apps-10-buttons.md
  docs/api-docs/apps/guide/apps-11-best-practices.md
  docs/api-docs/apps/guide/apps-12-requirements.md
  docs/api-docs/apps/guide/apps-13-publishing.md
  docs/api-docs/customers/current-customer-api.md
  docs/api-docs/headless/customers.md
  docs/bigcommerce-for-wordpress/setup/multi-site.md
  docs/stencil-docs/developing-further/google-analytics-enhanced-ecommerce.md
Labels: do-not-merge, awaiting-pe-sme-review

#1588 DEVDOCS-4205 Price List API
  docs/api-docs/catalog/price-list-overview.md
Labels: awaiting-peer-review
