Repository bigcommerce/dev-docs, pull requests merged in 2022-12, with the labels that each got.

#1692 #1691 Remove test flag on Stencil Start command && Add channelId and timeout flags
  docs/stencil-docs/installing-stencil-cli/stencil-cli-options-and-commands.md
Labels: external

#1688 DEVDOCS-4649: [update] Stencil CLI logging options
  docs/stencil-docs/installing-stencil-cli/stencil-cli-options-and-commands.md
Labels: ready-to-merge

#1679 DEVDOCS-4560: [add] Shipping Provider, add form_fields to destination
  docs/api-docs/store-management/shipping/shipping-provider-api.md
Labels: awaiting-css-cue

#1705 DEVDOCS-4277: [add] BNZ works with Payments API
  docs/api-docs/payments/payments-api-overview.md
Labels: awaiting-final-review, awaiting-peer-review, ready-to-merge

#1698 DEVDOCS-4647: [clarify] MSF theme parameters
  docs/msf/msf-api-guide.md
Labels: awaiting-creator-rereview, in-editorial-review

#1613 DEVDOCS-4400: [net new] Tax Rates Zones
  docs/api-docs/tax/tax-rates-zones.md
  toc.json
Labels: awaiting-creator-rereview, in-editorial-review

#1702 DEVDOCS-3933: [net new] Stencil, adding wallet buttons
  docs/stencil-docs/page-builder/wallet-buttons.md
Labels: awaiting-final-review, awaiting-peer-review
