Repository bigcommerce/dev-docs, pull requests merged in 2022-05, with the labels that each got.

#1484 DEVDOCS-3909: Update troubleshooting-your-setup.md
  docs/stencil-docs/installing-stencil-cli/troubleshooting-your-setup.md
Labels: awaiting-final-review, awaiting-peer-review

#1483 DEVDOCS-3890: Add Spanish language files
  docs/stencil-docs/localization/localizing-stores.md
Labels: awaiting-final-review, awaiting-pe-sme-review, awaiting-peer-review

#1458 DEVDOCS-3021: Add-examples-channel-webhooks
  docs/api-docs/apps/guide/apps-08-events.md
  docs/api-docs/cart-and-checkout/embedded-checkout-overview.md
  docs/api-docs/catalog/pricing-order-operation.md
  docs/api-docs/channels/channel-webhooks.md
  docs/api-docs/getting-started/best-practices.md
  docs/api-docs/getting-started/webhooks/about-webhooks.md
  docs/api-docs/getting-started/webhooks/webhook-events.md
  docs/api-docs/payments/payments-api-overview.md
Labels: awaiting-pe-sme-review, awaiting-creator-rereview

#1487 DEVDOCS-3803: Update payments-api-overview
  docs/api-docs/payments/payments-api-overview.md
Labels: awaiting-final-review, awaiting-pe-sme-review, awaiting-peer-review

#1488 Fixed errors
  docs/api-docs/channels/channel-webhooks.md
Labels: awaiting-final-review

#1490 DEVDOCS-3839-update-custom-templates.md
  docs/stencil-docs/storefront-customization/custom-templates.md
Labels: awaiting-peer-review

#1434 DEVDOCS-3665: broken links
  docs/legacy/v2-products/v2-v3.md
Labels: awaiting-creator-rereview, awaiting-peer-review

#1472 DEVDOCS-3869: Update toc.json
  toc.json
Labels: awaiting-final-review, ready-to-merge

#1474 DEVDOCS-3808: broken link to gql-playground
  docs/stencil-docs/reference-docs/front-matter-reference.md
Labels: awaiting-final-review

#1494 DEVDOCS-3021: Update channel-webhooks.md
  docs/api-docs/channels/channel-webhooks.md
  docs/api-docs/getting-started/webhooks/webhook-events.md
Labels: awaiting-final-review, ready-to-merge

#1485 DEVDOCS-3882: Update b2b-edition.md
  docs/partner-apps/bundleb2b/b2b-edition.md
Labels: awaiting-final-review, ready-to-merge

#1500 DEVDOCS-4090: Update best-practise guide
  docs/api-docs/getting-started/best-practices.md
Labels: external

#1496 DEVDOCS-3406b: GraphQL-related scope creep
  docs/api-docs/customers/customer-login-api.md
  docs/api-docs/getting-started/about-our-api.md
  docs/api-docs/storefront/graphql/graphql-api-overview.md
  docs/stencil-docs/getting-started/stencil-technology-stack.md
  docs/stencil-docs/javascript-and-event-hooks/adding-javascript.md
  docs/stencil-docs/javascript-and-event-hooks/customizing-javascript.md
  docs/stencil-docs/javascript-and-event-hooks/dynamic-content-rendering.md
Labels: awaiting-peer-review
