Repository bigcommerce/dev-docs, pull requests merged in 2022-11, with the labels that each got.

#1673 DEVDOCS-4572: [value add request ] Suggest ngrok to serve theme over https
  docs/stencil-docs/installing-stencil-cli/live-previewing-a-theme.md
Labels: in-editorial-review

#1675 DEVDOCS-4543 Early Hints
  docs/stencil-docs/reference-docs/handlebars-helpers-reference.md
  docs/stencil-docs/storefront-customization/early-hints.md
Labels: awaiting-pe-sme-review, awaiting-peer-review

#1648 DEVDOCS-4509: [update] Stencil, add new sort type for theme styles
  docs/stencil-docs/page-builder/configuration.md
  docs/stencil-docs/reference-docs/styles-and-properties.md
Labels: awaiting-final-review, from-engineering, in-editorial-review

#1683 DEVDOCS 4479: [add] Checkout SDK, add local payment test limitations
  docs/api-docs/building-checkouts/checkout-customizability.md
Labels: awaiting-final-review, in-editorial-review

#1682 DEVDOCS-4604: [add] Payments, add ref to Get stored instruments
  docs/api-docs/payments/payments-api-overview.md
Labels: awaiting-final-review, in-editorial-review
