Repository bigcommerce/dev-docs, pull requests merged in 2022-10, with the labels that each got.

#1637 DEVDOCS-4118 [maint.] Update stock changes to manual edit orders
  docs/api-docs/orders/orders-api-overview.md
Labels: ready-to-merge

#1657 DEVDOCS-4160, 4381: [update] Remove dates for sunsets in the past
  docs/api-docs/getting-started/deprecations-and-sunsets.md
Labels: awaiting-pe-sme-review, awaiting-peer-review

#1667 DEVDOCS-4566 [Update] BC4WP AMP deprecation notice
  docs/bigcommerce-for-wordpress/extending-the-plugin/amp-for-the-plugin.md
Labels: awaiting-peer-review

#1668 DEVDOCS-4535 [Update] Google AMP planned deprecation
  docs/stencil-docs/developing-further/google-amp.md
Labels: awaiting-peer-review

#1643 DEVDOCS-4558: [value add] Handlebars reference, specify inclusivity of forloop end number
  docs/stencil-docs/reference-docs/handlebars-helpers-reference.md
Labels: ready-to-merge

#1664 DEVDOCS-4036
  docs/api-docs/building-storefronts/abandoned-carts.md
  docs/api-docs/cart-and-checkout/open-source-checkout.md
  docs/api-docs/catalog/currencies/currencies-overview.md
  docs/api-docs/payments/payments-api-overview.md
  docs/api-docs/provider-apis/tax/overview.md
  docs/bigcommerce-for-wordpress/setup/multi-site.md
  docs/stencil-docs/deploying-a-theme/preparing-thumbnail-images.md
  docs/stencil-docs/localization/localizing-stores.md
  docs/stencil-docs/reference-docs/global-objects-and-properties.md
Labels: awaiting-final-review
