Repository bigcommerce/dev-docs, pull requests merged in 2022-09, with the labels that each got.

#1622 DEVDOCS-4425: [edit] Partner sandbox guide, add global regions
  docs/api-docs/partner/create-a-sandbox.md
Labels: awaiting-final-review, ready-to-merge

#1600 DEVDOCS-4395: [update] installation instructions for Stencil CLI
  docs/stencil-docs/installing-stencil-cli/installing-stencil.md
Labels: awaiting-final-review, ready-to-merge

#1628 DEVDOC-4243: Updated links to BigDesign content in 4 files
  docs/api-docs/apps/guide/apps-09-ui.md
  docs/api-docs/apps/guide/apps-12-requirements.md
  docs/api-docs/apps/tutorials/sample-app-next/step-1-setup.md
  docs/api-docs/apps/tutorials/sample-app-next/step-4-enhance-ux.md
Labels: awaiting-final-review

#1633 DEVDOCS-4047, DEVDOCS-4433: [navigation] Promotions & Customer Segmentation API beta, add to toc
  toc.json
Labels: do-not-merge, awaiting-css-cue

#1582 DEVDOCS-2898: [update] Document app callback JWTs
  docs/api-docs/apps/guide/apps-04-devloper-portal.md
  docs/api-docs/apps/guide/apps-05-oauth.md
  docs/api-docs/apps/guide/apps-06-callbacks.md
Labels: awaiting-final-review

#1638 DEVDOCS-4428: [update] Standardize references to the App Marketplace
  docs/api-docs/apps/guide/apps-01-introduction.md
  docs/api-docs/apps/guide/apps-04-devloper-portal.md
  docs/api-docs/apps/guide/apps-05-oauth.md
  docs/api-docs/apps/guide/apps-09-ui.md
  docs/api-docs/apps/guide/apps-11-best-practices.md
  docs/api-docs/apps/guide/apps-12-requirements.md
  docs/api-docs/apps/guide/apps-13-publishing.md
  docs/api-docs/cart-and-checkout/channels-sites-routes.md
  docs/api-docs/channels/building-channel-apps.md
  docs/api-docs/channels/channels-overview.md
  docs/api-docs/provider-apis/tax/overview.md
  docs/api-docs/store-management/shipping/shipping-provider-api.md
  docs/stencil-docs/customizing-checkout/checkout-confirmation-injection.md
  docs/stencil-docs/page-builder/third-party-widgets.md
Labels: ready-to-merge
