Repository bigcommerce/dev-docs, pull requests merged in 2023-10, with the labels that each got.

#2077 DEVDOCS-5062: [update]update community link
  docs/api-docs/apps/guide/apps-01-introduction.mdx
  docs/api-docs/partner/support.mdx
  docs/stencil-docs/deploying-a-theme/troubleshooting-theme-uploads.mdx
  docs/stencil-docs/getting-started/about-stencil.mdx
Labels: awaiting-peer-review

#2078 DEVDOCS-5493: [update] add webhook cleanup policy
  docs/api-docs/webhooks/about-webhooks.mdx
Labels: awaiting-pe-sme-review, awaiting-peer-review

#2079 DEVDOCS-5454 [Update] Add 499 response code
  docs/api-docs/getting-started/api-status-codes.mdx
Labels: awaiting-peer-review

#2075 DEVDOCS-5502: [update] Resized images and add limits
  docs/api-docs/partner/create-a-sandbox.mdx
Labels: awaiting-pe-sme-review

#2071 DEVDOCS-5505: [Update] Clarified text re. correlating request and edi…
  docs/api-docs/headless/carts.mdx
  docs/api-docs/headless/checkout.mdx
  docs/api-docs/headless/orders.mdx
  docs/api-docs/headless/overview.mdx
  docs/api-docs/headless/tutorial.mdx
  docs/api-docs/storefront/graphql/graphql-carts-and-checkout.mdx
Labels: awaiting-peer-review

#2084 DEVDOCS-5571: [update] remove feature-complete callout
  docs/api-docs/storefront/graphql/graphql-api-examples.mdx
  docs/api-docs/storefront/graphql/graphql-api-overview.mdx
Labels: awaiting-pse-review, awaiting-peer-review

#2072 DEVDOCS-5425 [new]: Tax Settings API, add setting
  docs/api-docs/tax/tax-settings.mdx
Labels: awaiting-css-cue

#2089 DEVDOCS-5578: [update] update node-sass date
  docs/stencil-docs/installing-stencil-cli/installing-stencil.mdx
  docs/stencil-docs/installing-stencil-cli/stencil-cli-options-and-commands.mdx
  docs/stencil-docs/installing-stencil-cli/troubleshooting-your-setup.mdx
Labels: awaiting-pse-review, awaiting-peer-review
