Repository bigcommerce/dev-docs, pull requests merged in 2023-02, with the labels that each got.

#1796 DEVDOCS-4768: [suggest] Products V2, PR 1793
  docs/legacy/v2-catalog-products/v2-product-sku.md
  docs/legacy/v2-catalog-products/v2-products.md
Labels: awaiting-peer-review

#1746 DEVDOCS-4719: [migrate] Tax V3 API & Tax Provider API, migrate syntax
  docs/api-docs/provider-apis/tax/overview.mdx
  docs/api-docs/tax/tax-properties.md
  docs/api-docs/tax/tax-properties.mdx
  docs/api-docs/tax/tax-rates-zones.md
  docs/api-docs/tax/tax-rates-zones.mdx
  docs/api-docs/tax/tax-settings.mdx
Labels: awaiting-final-review, linter-added

#1747 DEVDOCS-4719: [migrate] Customers
  docs/api-docs/customers/channel-specific-customers.mdx
  docs/api-docs/customers/current-customer-api.mdx
  docs/api-docs/customers/customer-login-api.mdx
  docs/api-docs/customers/customers-subscribers-overview.mdx
  docs/api-docs/customers/passwordless-login.mdx
Labels: awaiting-final-review, linter-added

#1748 DEVDOCS-4719:[migrate] Currencies
  docs/api-docs/catalog/currencies/currencies-overview.mdx
  docs/api-docs/catalog/currencies/how-currencies-work.mdx
  docs/api-docs/catalog/price-list-overview.mdx
  docs/api-docs/catalog/pricing-order-operation.mdx
Labels: awaiting-final-review, linter-added

#1752 DEVDOCS-4719: [migrate] BODL, migrate syntax
  docs/api-docs/analytics/bodl-for-storefronts.mdx
Labels: awaiting-final-review, linter-added

#1788 DEVDOCS-4719: [migrate] Blueprint Reference, migrate syntax
  docs/legacy/blueprint-reference/blueprint-layouts.md
  docs/legacy/blueprint-reference/blueprint-layouts.mdx
  docs/legacy/blueprint-reference/blueprint-panels.md
  docs/legacy/blueprint-reference/blueprint-panels.mdx
  docs/legacy/blueprint-reference/blueprint-snippets.md
  docs/legacy/blueprint-reference/blueprint-snippets.mdx
Labels: awaiting-final-review, linter-added

#1775 DEVDOCS-4719: [migrate] Checkout Consignment, migrate syntax
  docs/api-docs/building-checkouts/checkout-consignment.mdx
  docs/api-docs/building-checkouts/checkout-customizability.mdx
Labels: awaiting-final-review, linter-added

#1776 DEVDOCS-4719: [migrate] Orders
  docs/api-docs/orders/order-refunds.mdx
  docs/api-docs/orders/orders-api-overview.mdx
  docs/api-docs/orders/orders-overview.md
  docs/api-docs/orders/orders-overview.mdx
Labels: awaiting-final-review, linter-added

#1777 DEVDOCS-4719: [migrate] Headless, migrate syntax
  docs/api-docs/headless/carts.mdx
  docs/api-docs/headless/channels.mdx
  docs/api-docs/headless/checkout.mdx
  docs/api-docs/headless/customers.mdx
  docs/api-docs/headless/orders.mdx
  docs/api-docs/headless/overview.mdx
  docs/api-docs/headless/pci-compliance.mdx
  docs/api-docs/headless/products.mdx
  docs/stencil-docs/reference-docs/common-objects.mdx
Labels: awaiting-final-review, linter-added

#1780 DEVDOCS-4719: [migrate] Bundle B2B, migrate syntax
  docs/partner-apps/bundleb2b/b2b-edition.mdx
Labels: awaiting-final-review, linter-added

#1781 DEVDOCS-4719: [migrate] Contextual Filters, migrate syntax
  docs/api-docs/management-apis/contextual-filters.md
  docs/api-docs/management-apis/contextual-filters.mdx
Labels: awaiting-final-review, linter-added

#1786 DEVDOCS-4719: [migrate] Building Storefronts, migrate syntax
  docs/api-docs/building-storefronts/abandoned-carts.mdx
  docs/api-docs/building-storefronts/nextjs-commerce-guide.mdx
Labels: awaiting-final-review, linter-added

#1791 DEVDOCS-4719 : [migrate] Available APIs, syntax
  docs/api-docs/getting-started/available-apis.mdx
Labels: complex

#1751 DEVDOCS-4719: [migrate] Store Logs API, migrate syntax
  docs/api-docs/store-logs/store-logs.mdx
Labels: awaiting-final-review, linter-added

#1753 DEVDOCS-4719: [migrate] MSF, migrate syntax
  docs/msf/managing-store-configuration.mdx
  docs/msf/msf-api-guide.mdx
  docs/msf/msf-app-compatibility.mdx
  docs/msf/msf-overview.mdx
Labels: awaiting-final-review, linter-added

#1763 DEVDOCS-4719: [migrate] Payments API, migrate syntax
  docs/api-docs/payments/payments-api-overview.mdx
Labels: awaiting-final-review, linter-added

#1789 DEVDOCS-4719: [migrate] empty file, change file type
  docs/api-docs/void/void.mdx
Labels: awaiting-final-review, linter-added

#1790 DEVDOCS-4719: [migrate] capture.md, change file type
  docs/api-docs/capture/capture.mdx
Labels: awaiting-final-review, linter-added

#1798 DEVDOCS-4719: [migrate] Stoplight links
  docs/api-docs/headless/customers.mdx
  docs/partner-apps/bundleb2b/b2b-edition.mdx
Labels: awaiting-peer-review, migration-ready
