Repository bigcommerce/dev-docs, pull requests merged in 2023-12, with the labels that each got.

#2112 DEVDOCS-5619: [Update] becoming-a-partner.mdx
  docs/api-docs/partner/becoming-a-partner.mdx
Labels: awaiting-peer-review

#2080 DEVDOCS-2944 [new]: Non-Store Owners can install/uninstall apps
  docs/api-docs/apps/guide/apps-05-oauth.mdx
  docs/api-docs/apps/guide/apps-06-callbacks.mdx
  docs/api-docs/apps/guide/apps-07-users.mdx
  docs/api-docs/apps/guide/apps-13-publishing.mdx
  docs/api-docs/getting-started/api-status-codes.mdx
  docs/api-docs/getting-started/rest-api-authentication.mdx
  docs/api-docs/partner/subscriptions/foundation-guide.mdx
Labels: awaiting-css-cue

#2113 DEVDOCS-5596: [Update] theme variation limit
  docs/stencil-docs/page-builder/configuration.mdx
Labels: awaiting-peer-review

#2114 DEVDOCS-5645: [update] add webhook requirements
  docs/api-docs/webhooks/about-webhooks.mdx
Labels: manual-merge, manual-migrate

#2116 DEVDOCS-5675: [update] add graphQL behavior
  docs/api-docs/storefront/graphql/graphql-api-overview.mdx
Labels: awaiting-peer-review, merge-before-migration

#2117 [DEVDOCS-5647]: [deprecate] BigCommerce for WordPress, Remove MSF references in BigCommerce for WP
  docs/bigcommerce-for-wordpress/getting-started/install.mdx
  docs/bigcommerce-for-wordpress/setup/multi-site.mdx
Labels: awaiting-peer-review

#2110 (no ticket): [repo] PR template, add release notes section
  pull_request_template.md
Labels: merge-before-migration

#2123 DEVDOCS-4492: [update] MSF Overview, add KB reference
  docs/msf/msf-overview.mdx
Labels: awaiting-peer-review, merge-before-migration
