Repository bigcommerce/dev-docs, pull requests merged in 2023-06, with the labels that each got.

#1954 DEVDOCS-5063: [revise] BigCommerce For WordPress, Troubleshooting guide revision
  docs/bigcommerce-for-wordpress/setup/troubleshooting.mdx
Labels: awaiting-pse-review, awaiting-peer-review

#1953 DEVDOCS-5037: [new] GraphQL Cart and Checkout
  docs/api-docs/storefront/graphql/graphql-carts-and-checkout.mdx
Labels: do-not-merge, awaiting-css-cue

#1977 DEVDOCS-5115: [revise] Price Lists, Add webhook notes to price lists overview
  docs/api-docs/catalog/price-list-overview.mdx
Labels: awaiting-peer-review

#1976 DEVDOCS-5107: [update] hash definition
  docs/api-docs/webhooks/webhook-events.mdx
Labels: awaiting-peer-review

#1986 PROJECT-4730: [update] App Extensions, add to OAuth scopes
  docs/api-docs/getting-started/rest-api-authentication.mdx
Labels: awaiting-css-cue
