Repository bigcommerce/dev-docs, pull requests merged in 2023-08, with the labels that each got.

#2035 DEVDOCS-5236: [update] update blocklisting mechanism info
  docs/api-docs/webhooks/about-webhooks.mdx
Labels: awaiting-peer-review

#2040 DEVDOCS-5154: [update] Update blueprint-snippets.mdx
  docs/legacy/blueprint-reference/blueprint-snippets.mdx
Labels: awaiting-peer-review

#2038 DEVDOCS-4953: [revise] audit and rewrite
  docs/stencil-docs/customizing-checkout/checkout-sdk-example.mdx
  docs/stencil-docs/customizing-checkout/checkout-sdk-quickstart.mdx
  docs/stencil-docs/customizing-checkout/open-source-checkout.mdx
Labels: awaiting-peer-review

#2044 DEVDOCS-4999: [update] Added sites webhooks
  docs/api-docs/channels/channel-webhooks.mdx
Labels: ready-to-merge

#2033 fix 404s for stencil docs
  docs/stencil-docs/page-builder/wallet-buttons.mdx
  docs/stencil-docs/reference-docs/handlebars-helpers-reference.mdx
  docs/stencil-docs/reference-docs/stencil-utils-api-reference.mdx
  docs/stencil-docs/storefront-customization/WCAG-compliance-levels.mdx
  docs/stencil-docs/storefront-customization/custom-templates.mdx
  docs/stencil-docs/storefront-customization/theme-accessibility.mdx
Labels: awaiting-peer-review

#2041 DEVDOCS-5303: [update] add error code
  docs/api-docs/getting-started/api-status-codes.mdx
Labels: awaiting-pe-sme-review, awaiting-peer-review

#2047 DEVDOCS-4795: replace site_id with channel_id for widgets
  docs/msf/msf-api-guide.mdx
Labels: awaiting-peer-review

#1969 (no ticket): [update] Catalog Price, fix broken IMG URL
  docs/stencil-docs/developing-further/catalog-price-object.mdx
Labels: awaiting-peer-review

#2057 DEVDOCS-4090 + revisions: [update] Many, platform engagement docs
  .cspell.json
  .style/.spelling
  .style/core-glossary.txt
  .style/skip-list.txt
  docs/api-docs/apps/guide/apps-11-best-practices.mdx
  docs/api-docs/getting-started/about-our-api.mdx
  docs/api-docs/getting-started/authentication.mdx
  docs/api-docs/getting-started/best-practices.mdx
  docs/api-docs/getting-started/making-requests.mdx
  docs/api-docs/headless/overview.mdx
  docs/stencil-docs/reference-docs/front-matter-reference.mdx
Labels: awaiting-peer-review
