Repository bigcommerce/dev-docs, pull requests merged in 2023-01, with the labels that each got.

#1714 DEVDOCS-4680: [update] Tax Rates & Zones, more about default tax zone
  docs/api-docs/tax/tax-rates-zones.md
Labels: awaiting-creator-rereview, in-editorial-review

#1711 DEVDOCS-4648: [update] Subscription Foundation, add multi-tenant graphic
  docs/api-docs/partner/subscriptions/foundation-guide.md
Labels: awaiting-creator-rereview

#1712 DEVDOCS-4660: [update] Theme Styles and Properties, clarify force_reload
  docs/stencil-docs/reference-docs/styles-and-properties.md
Labels: awaiting-final-review

#1727 DEVDOCS-4710: [update] Catalog V2 API, fix broken link
  docs/legacy/v2-catalog-products/v2-custom-fields.md
Labels: awaiting-final-review

#1726 DEVDOCS-4711: [update] Handlebars reference, add strReplace helper
  docs/stencil-docs/reference-docs/handlebars-helpers-reference.md
Labels: awaiting-final-review

#1718 DEVDOCS-4688: [new] Stencil Ref, add getPageByGQL
  docs/stencil-docs/reference-docs/stencil-utils-api-reference.md
Labels: awaiting-final-review, in-editorial-review

#1631 DEVDOCS-4429: [new] Headless Carts, add locale info; [update] Customer Login
  docs/api-docs/customers/customer-login-api.md
  docs/api-docs/headless/carts.md
Labels: in-editorial-review

#1738 DEVDOCS-4756: [update] BC4WP Setup, update list of default OAuth scope settings
  docs/bigcommerce-for-wordpress/setup/multi-site.md
Labels: awaiting-pe-sme-review, awaiting-peer-review

#1737 DEVDOCS-4759: [remove] Live Previewing a Theme, remove outdated YouTube video
  docs/stencil-docs/installing-stencil-cli/live-previewing-a-theme.md
Labels: awaiting-final-review, awaiting-peer-review

#1739 DEVDOCS-4666: [update] Payments API, clarify no test payment gateway support
  docs/api-docs/payments/payments-api-overview.md
Labels: awaiting-final-review, awaiting-peer-review
