Repository bigcommerce/dev-docs, pull requests merged in 2023-04, with the labels that each got.

#1735 DEVDOCS-4620: [new] Data Layer API, add new doc
  docs/api-docs/analytics/bodl-for-storefronts.mdx
  docs/api-docs/analytics/data-layer-api.mdx
  docs/api-docs/getting-started/authentication.mdx
  docs/api-docs/getting-started/rest-api-authentication.mdx
Labels: awaiting-final-review

#1879 DEVDOCS-4864: [update] BC4WP, OAuth scopes
  docs/bigcommerce-for-wordpress/setup/multi-site.mdx
Labels: awaiting-creator-rereview

#1882 DEVDOCS-4194: [remove] Orders, duplicate orders-overview doc
  docs/api-docs/orders/orders-overview.mdx
Labels: awaiting-creator-rereview

#1892 DEVDOCS-4876: [update] Apps Quick Start, add remove_user callback config
  docs/api-docs/apps/apps-quick-start.mdx
Labels: awaiting-peer-review
