Repository bigcommerce/dev-docs, pull requests merged in 2023-07, with the labels that each got.

#1993 DEVDOCS-4831: [update] getImageManagerImageSrcset
  docs/stencil-docs/reference-docs/handlebars-helpers-reference.mdx
Labels: awaiting-peer-review

#1838 DEVDOCS-4714: [update] BODL, add 5 bodl events
  docs/api-docs/analytics/bodl-for-storefronts.mdx
Labels: do-not-merge

#1992 PSE-694:[update] Fix Readme 404 subscription foundation
  docs/api-docs/partner/subscriptions/foundation-guide.mdx
Labels: awaiting-peer-review

#1996 DEVDOCS-5177: [Revise] change title for defining-global-styles.mdx
  docs/stencil-docs/configure-store-design-ui/defining-global-styles.mdx
Labels: awaiting-peer-review

#2017 DEVDOCS-5190: [update] Wallet Buttons, support themes <6.7
  docs/stencil-docs/page-builder/wallet-buttons.mdx
Labels: awaiting-peer-review

#2018 DEVDOCS-3904: [update] clarify structure for destination
  docs/api-docs/webhooks/setting-up-webhooks.mdx
Labels: awaiting-peer-review

#2008 DEVDOCS-5159 [revise]: BC4WordPress, Troubleshooting, update with new guidance; tokens, error logs, cron jobs
  docs/bigcommerce-for-wordpress/setup/troubleshooting.mdx
Labels: awaiting-pe-sme-review, awaiting-peer-review
