Repository bigcommerce/dev-docs, pull requests merged in 2023-03, with the labels that each got.

#1800 DEVDOCS-4719: [migrate] BC for WordPress, 404 links
  docs/bigcommerce-for-wordpress/extending-the-plugin/amp-for-the-plugin.mdx
  docs/bigcommerce-for-wordpress/extending-the-plugin/proxy-rest-api-endpoints.mdx
  docs/bigcommerce-for-wordpress/getting-started/app-compatibility.mdx
  docs/bigcommerce-for-wordpress/getting-started/site-launch-checklist.mdx
Labels: awaiting-final-review

#1743 DEVDOCS-4763
  docs/stencil-docs/customizing-checkout/open-checkout-quick-start.mdx
Labels: awaiting-final-review

#1831 DEVDOCS-4812: [new] GraphQL Users API, add overview
  docs/api-docs/users/overview.mdx
Labels: awaiting-peer-review

#1811 fix(shipping): SHIPPING-700 Remove unused x-auth-token header
  docs/api-docs/store-management/shipping/shipping-provider-api.mdx
Labels: awaiting-final-review

#1828 DEVDOCS-4562:[Update] adyenv3
  docs/api-docs/payments/payments-api-overview.mdx
Labels: awaiting-pe-sme-review, awaiting-peer-review

#1819 DEVDOCS-4819:[update] channels.mdx
  docs/api-docs/headless/channels.mdx
Labels: awaiting-pe-sme-review, awaiting-peer-review

#1730 DEVDOCS-4750: [update] Handlebars helpers, add JSONparseSafe
  docs/stencil-docs/reference-docs/handlebars-helpers-reference.mdx
Labels: awaiting-final-review

#1734 DEVDOCS-4704: [update] Global objects, create new section for urls
  docs/stencil-docs/reference-docs/global-objects-and-properties.mdx
  docs/stencil-docs/reference-docs/handlebars-helpers-reference.mdx
Labels: awaiting-final-review
